# tasks file for ./roles/docker
- name: Create a Docker swarm if not exists
  shell: docker swarm init --advertise-addr {{ ip_address }}
  ignore_errors: yes

- name: checking whether blogger service is exists or not
  shell: docker node ps -f name=web_blogger
  register: result

- name: Delete Blog service
  shell: docker service rm web_blogger
  when: result.stdout_lines|length > 1

- name: Create Blog service
  shell: docker service create --name web_blogger -p 12321:8000 blog:10
