# tasks file for ./roles/docker
- name: Create a Docker swarm if not exists
  shell: docker swarm init --advertise-addr {{ ip_address }}
  ignore_errors: yes

- name: checking whether blogger service is exists or not
  shell: docker node ps -f name=blog
  register: result

- name: Delete Blog service
  shell: docker service rm blog
  when: result.stdout_lines|length > 1

- name: Create JSON file content
  shell: cat Blogger/project/config.json
  register: result

- name: save the Json data to a Variable as a Fact
  set_fact:
    jsondata: "{{ result.stdout | from_json }}"

- name: Listen port number from config.json
  set_fact:
    admin_Port: "{{ jsondata | json_query(jmesquery) }}"
  vars:
    jmesquery: 'params.port_number'

- name: Create Blog service
  shell: docker service create --name blog -p {{ admin_Port }}:8000 --replicas 2 blog:10