"""update new coloumn

Revision ID: 3f48bade3af1
Revises: f01c47ead91c
Create Date: 2020-12-12 01:04:46.832653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f48bade3af1'
down_revision = 'f01c47ead91c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts') as batch_op:
        batch_op.drop_column('alt_phone_no')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'alt_phone_no')
    # ### end Alembic commands ###
