"""update new coloumn

Revision ID: eb0dac0de1c6
Revises: 3f48bade3af1
Create Date: 2020-12-12 01:15:07.597753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb0dac0de1c6'
down_revision = '3f48bade3af1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts') as batch_op:
        batch_op.drop_column('alt_phone_no')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('alt_phone_no', sa.VARCHAR(length=10), nullable=True))
    # ### end Alembic commands ###
