"""removed the exta field

Revision ID: f01c47ead91c
Revises: de8b7ec77f15
Create Date: 2020-12-12 00:44:14.595648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f01c47ead91c'
down_revision = 'de8b7ec77f15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts') as batch_op:
        batch_op.drop_column('alt_phone_no')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('alt_phone_no', sa.VARCHAR(length=10), nullable=False))
    # ### end Alembic commands ###
